[project]
name = "pyGEONOSIS"
version = "0.2.0"
description = "A tool for simulating the spectra of any diatomic molecule."
readme = "README.md"
requires-python = "==3.13.5"
dependencies = [
    "hamilterm",
    "matplotlib==3.10.3",
    "numpy==2.3.1",
    "polars==1.31.0",
    "py3nj",
    "pyqtdarktheme==2.1.0",
    "pyqtgraph==0.13.7",
    # Pyside6 version 6.9.1 breaks plotting entirely. Pin all versions to prevent future breakage.
    # See https://github.com/pyqtgraph/pyqtgraph/issues/3321 and https://bugreports.qt.io/browse/PYSIDE-3115.
    # Fixed in PyQt 6.9.2, just waiting for the release.
    "pyside6-essentials==6.9.0",
    "scipy==1.16.0",
]

[tool.basedpyright]
typeCheckingMode = "basic"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = [
    "A",
    "ARG",
    "C4",
    "C90",
    "D",
    "E",
    "FIX",
    "I",
    "N",
    "NPY",
    "PL",
    "RET",
    "SIM",
    "TC",
    "UP",
    "W",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.uv.sources]
hamilterm = { git = "https://github.com/nategphillips/hamilterm", rev = "c3334df9546b9faad4e6476b955f2c2d9f54a718" }
py3nj = { git = "https://github.com/fujiisoup/py3nj", rev = "098e40e433d6c1f32b1b488519bbae40f40b812b" }

[tool.uv]
required-version = "==0.8.5"
